'use client';
import { useEffect, useState, useCallback, useRef } from 'react';
import { ArrowUp,ArrowDown,Plus,Trash2,ExternalLink } from 'lucide-react';
import ReviewsEditor from './reviews-editor';
import type { SiteContent } from '@/lib/content';
import { validateContent } from '@/lib/validation';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel } from '@/components/ui/alert-dialog';
export default function Editor({initial,revision}:{initial:SiteContent;revision:number}){
 const [data,setData]=useState(initial),[version,setVersion]=useState(revision),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[remove,setRemove]=useState<string|null>(null);
 const state=useRef({data,version});state.current={data,version};
 const update=(patch:Partial<SiteContent>)=>{setData(d=>({...d,...patch}));setDirty(true)};
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const save=useCallback(async()=>{setBusy(true);setStatus('');try{const current=state.current;validateContent(current.data);const res=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:current.data,revision:current.version})});const result=await res.json() as {error?:string;revision:number;src:string};if(!res.ok)throw new Error(result.error);setVersion(result.revision);setDirty(false);setStatus('Зміни збережено. Вони вже на сайті.');return {revision:result.revision}}catch(e){const error=e instanceof Error?e.message:'Не вдалося зберегти.';setStatus(error);throw e}finally{setBusy(false)}},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void}}).modelContext;if(!context)return;const controller=new AbortController();try{context.registerTool({name:'save_portfolio_changes',title:'Зберегти зміни портфоліо',description:'Save the currently edited portfolio content to the live site. Same action as the Save button.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return save()}},{signal:controller.signal})}catch{ /* Browser support is optional. */ }return()=>controller.abort()},[save]);
 async function upload(file:File|undefined,target:'work'|'portrait'|'studio'){
 if(!file)return;setBusy(true);setStatus('Завантажуємо фото…');try{
 if(file.size>8*1024*1024)throw new Error('Фото має бути до 8 МБ.');
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Оберіть JPG, PNG або WebP.');
 const res=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':file.type},body:file});const result=await res.json() as {error?:string;revision:number;src:string};if(!res.ok)throw new Error(result.error);
 if(target==='work')update({works:[...data.works,{id:crypto.randomUUID(),src:result.src,alt:'Нова робота',category:'Тату'}]});else update({[target]:result.src});setStatus('Фото додано. Збережи зміни, щоб показати його на сайті.');
 }catch(e){setStatus(e instanceof Error?e.message:'Помилка завантаження.')}finally{setBusy(false)}
 }
 const move=(index:number,delta:number)=>{const list=[...data.works];[list[index],list[index+delta]]=[list[index+delta],list[index]];update({works:list})};
 const fields:[keyof Pick<SiteContent,'name'|'intro'|'biography'|'price'|'address'|'instagram'|'phone'|'email'|'telegram'|'tiktok'|'mapsUrl'|'openingHours'>,string,number][]=[['name','Ім’я майстра',60],['biography','Про майстра',1500],['price','Вартість і умови',1500],['address','Адреса студії',250],['phone','Телефон',30],['email','Email',254],['telegram','Telegram (https://t.me/...)',200],['instagram','Instagram студії',200],['tiktok','TikTok',200],['mapsUrl','Google Maps',1000],['openingHours','Графік роботи',150]];
 return <main className="editor wrap"><header className="editor-header"><div><p className="eyebrow brand-name">NA GOLCI</p><h1>Редактор сайту</h1></div><a className="text-link" href="/" target="_blank" rel="noreferrer">Переглянути сайт <ExternalLink size={17}/></a></header>
 <div className="editor-save"><span>{dirty?'Є незбережені зміни':'Усі зміни збережено'}</span><button className="primary-link" disabled={busy||!dirty} onClick={()=>{void save().catch(()=>{})}}>{busy?'Зачекай…':'Зберегти зміни'}</button></div><p role="status" className="editor-status">{status}</p>
 <fieldset disabled={busy}><legend className="sr-only">Редагування вмісту</legend><section className="editor-section"><h2>Тексти й контакти</h2><p>Залиш контактне поле порожнім, щоб приховати його на сайті.</p><div className="editor-fields">{fields.map(([key,label,max])=><label key={key}>{label}{['name','address','instagram','phone','email','telegram','tiktok','mapsUrl','openingHours'].includes(key)?<input value={data[key]} maxLength={max} onChange={e=>update({[key]:e.target.value})}/>:<textarea value={data[key]} rows={4} maxLength={max} onChange={e=>update({[key]:e.target.value})}/>}</label>)}</div></section>
 <section className="editor-section"><h2>Майстер і студія</h2><div className="editor-images">{(['portrait','studio'] as const).map(key=><label key={key}>{key==='portrait'?'Портрет майстра':'Фото студії'}<img src={data[key]} alt={key==='portrait'?'Поточний портрет':'Поточне фото студії'}/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0],key);e.target.value=''}}/></label>)}</div></section>
 <section className="editor-section"><h2>Галерея</h2><p>Стрілками змінюй порядок робіт у галереї. До 100 робіт, JPG / PNG / WebP до 8 МБ.</p><label className="upload-label"><Plus size={19}/> Додати роботу<input type="file" accept="image/jpeg,image/png,image/webp" disabled={data.works.length>=100} onChange={e=>{void upload(e.target.files?.[0],'work');e.target.value=''}}/></label><div className="editor-works">{data.works.map((w,i)=><article key={w.id} className="editor-work"><img src={w.src} alt={w.alt}/><div><label>Опис фото<input value={w.alt} maxLength={150} onChange={e=>update({works:data.works.map(x=>x.id===w.id?{...x,alt:e.target.value}:x)})}/></label><label>Напрям<input value={w.category} maxLength={60} onChange={e=>update({works:data.works.map(x=>x.id===w.id?{...x,category:e.target.value}:x)})}/></label></div><div className="editor-controls"><button className="icon-button" aria-label={`Підняти: ${w.alt}`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={18}/></button><button className="icon-button" aria-label={`Опустити: ${w.alt}`} disabled={i===data.works.length-1} onClick={()=>move(i,1)}><ArrowDown size={18}/></button><button className="icon-button" aria-label={`Прибрати: ${w.alt}`} disabled={data.works.length<=1} onClick={()=>setRemove(w.id)}><Trash2 size={18}/></button></div></article>)}</div></section><ReviewsEditor reviews={data.reviews} onChange={reviews=>update({reviews})}/></fieldset>
 <AlertDialog open={remove!==null} onOpenChange={open=>{if(!open)setRemove(null)}}><AlertDialogContent><AlertDialogTitle>Прибрати роботу з галереї?</AlertDialogTitle><AlertDialogDescription>Зміна з’явиться на сайті після збереження.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Залишити</AlertDialogCancel><AlertDialogAction onClick={()=>{update({works:data.works.filter(w=>w.id!==remove)});setRemove(null)}}>Прибрати</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
