'use client';
import {ArrowUp,ArrowDown,Plus,Trash2} from 'lucide-react';
import type {Review} from '@/lib/reviews';
export default function ReviewsEditor({reviews,onChange}:{reviews:Review[];onChange:(reviews:Review[])=>void}){
 const update=(id:string,patch:Partial<Review>)=>onChange(reviews.map(r=>r.id===id?{...r,...patch}:r));
 const move=(i:number,delta:number)=>{const next=[...reviews];[next[i],next[i+delta]]=[next[i+delta],next[i]];onChange(next)};
 return <section className="editor-section"><h2>Відгуки Google</h2><p>Короткі цитати до 25 слів із посиланням на оригінал. Порожній список приховує розділ. Зміни з’являться на сайті після збереження.</p><button type="button" className="text-link" disabled={reviews.length>=30} onClick={()=>onChange([...reviews,{id:crypto.randomUUID(),author:'',quote:'',rating:5,originalLanguage:'uk',url:''}])}><Plus size={18}/> Додати відгук</button>
 <div className="review-editor-list">{reviews.map((r,i)=><article key={r.id} className="review-editor-card"><h3>Відгук {i+1}</h3><div className="editor-fields"><label>Автор<input value={r.author} maxLength={100} onChange={e=>update(r.id,{author:e.target.value})}/></label><label>Оцінка<select value={r.rating} onChange={e=>update(r.id,{rating:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Цитата українською<textarea value={r.quote} rows={4} maxLength={600} onChange={e=>update(r.id,{quote:e.target.value})}/><small>{r.quote.trim()?r.quote.trim().split(/\s+/).length:0} / 25 слів</small></label><label>Мова оригіналу<input value={r.originalLanguage} maxLength={40} onChange={e=>update(r.id,{originalLanguage:e.target.value})}/><small>uk — українська, ru — російська, en — англійська. Для іншої мови: «польської», «німецької».</small></label><label>Посилання на відгук<input type="url" value={r.url} maxLength={1000} onChange={e=>update(r.id,{url:e.target.value})}/></label></div><div className="review-editor-controls"><button type="button" className="icon-button" disabled={i===0} aria-label={`Підняти відгук ${i+1}`} onClick={()=>move(i,-1)}><ArrowUp size={18}/></button><button type="button" className="icon-button" disabled={i===reviews.length-1} aria-label={`Опустити відгук ${i+1}`} onClick={()=>move(i,1)}><ArrowDown size={18}/></button><button type="button" className="icon-button" aria-label={`Прибрати відгук ${i+1}`} onClick={()=>onChange(reviews.filter(x=>x.id!==r.id))}><Trash2 size={18}/></button></div></article>)}</div></section>
}
