export type Review = {id:string;author:string;quote:string;rating:number;originalLanguage:string;url:string};
// Ukrainian originals from Google Maps: 10 verified 2026-09-27; 5 added 2026-09-30.
// Quote spacing is lightly normalized; wording is preserved.
// Google displayed relative dates only; no exact publication dates are inferred.
export const reviewsUrl='https://www.google.com/maps/place/%D1%82%D0%B0%D1%82%D1%83+%D1%81%D0%B0%D0%BB%D0%BE%D0%BD+NA+GOLCI/@50.46621,30.5135172,16z/data=!4m8!3m7!1s0x40d4cf82f685f7d3:0x701bfc8305c4b8c0!8m2!3d50.4664465!4d30.5104729!9m1!1b1!16s%2Fg%2F11f8bsbz1y';
export const initialReviews:Review[]=[
{id:'sasha',author:'Саша Диденко',rating:5,originalLanguage:'uk',quote:'Робила в Паші вже два тату — і обидва вийшли просто чудово. Все дуже якісно, акуратно й швидко. Атмосфера під час сеансів спокійна й довірлива, мені було комфортно з першої хвилини. Паша все пояснює, прислухається до побажань і реально допомагає зробити малюнок ідеальним. Дуже задоволена результатом і досвідом загалом!',url:'https://maps.app.goo.gl/6CuW9LHxnr8MjdUP8'},
{id:'yana',author:'Yana Yakimets',rating:5,originalLanguage:'uk',quote:'Тату-студія дійсно дуже затишна, а майстер Павло дуже комфортна та цікава людина, з якою завжди є про що поговорити. Робила вже три татуювання у нього і максимально задоволена, стерильність і швидке загоєння гарантоване, а для мене це грає дуже велику роль. Дякую, Павле!',url:'https://maps.app.goo.gl/SDUmAXYD6xoUi5D97'},
{"id":"alina-momot","author":"Alina Momot","rating":5,"originalLanguage":"uk","quote":"Дуже вдячна майстру за професіоналізм і уважність до деталей. Завжди комфортно почуваюся в салоні — чисто, затишно, спокійна атмосфера. Особливо ціную тонке відчуття композиції: майстер завжди допомагає знайти найвдаліше розташування для тату, щоб воно виглядало гармонійно з урахуванням розміру й форми. Результат щоразу перевершує очікування. Рекомендую щиро!","url":"https://maps.app.goo.gl/guhWwF9BPmCdjG9XA"},
{id:'bodia',author:'Бодя Семенченко',rating:5,originalLanguage:'uk',quote:'Зробив у Паші 2 тату. Максимально задоволений результатом. Завжди раджу та буду радити його всім, справжній майстер свого діла👍🏻',url:'https://maps.app.goo.gl/8EnrQj2sfMcZemc99'},
// English original verified in Google Maps on 2026-10-05.
{id:'vlada-korobchynska',author:'Vlada korobchynska',rating:5,originalLanguage:'en',quote:'Best art skills, work quality and price range. Not the first time here and definitely not the last. My favourite tattoo artist',url:'https://maps.app.goo.gl/QSF1xzi5Lbvn3qoh8'},
{id:'darya-shevtsova',author:'Darya Shevtsova',rating:5,originalLanguage:'uk',quote:'Хочу поділитися враженнями про тату-салон і подякувати майстру Павлу\nЦе просто ТОП майстер! Професіонал з великої літери — уважний до деталей, працює акуратно, все стерильно й безпечно.\nСаме той майстер, до якого хочеться повертатися!',url:'https://maps.app.goo.gl/awp1hDpA4dRkYqR98'},
{"id":"mikhaela-denysenko","author":"Міхаела Денисенко","quote":"У Павла робила всі свої тату, а їх у мене 4. Майстер вищої категорії! Уважний до клієнта, враховує всі побажання. Використовуж висококласні матеріали, і результат відповідно теж на рівні!\nДо того ж дуже приємний у спілкуванні. Однозначно раджу Павла!!!!","rating":5,"originalLanguage":"uk","url":"https://maps.app.goo.gl/tzGegQ14nT4i9eAJ6"},
{id:'darina',author:'Darina Onoprienko',rating:5,originalLanguage:'uk',quote:'Залишилася дуже задоволена роботою! Все акуратно, стерильно і з увагою до деталей)',url:'https://maps.app.goo.gl/ota5vSvCg5pmU5nNA'},
{"id":"natali","author":"Natali","rating":5,"originalLanguage":"uk","quote":"Вже який рік бʼю тату у Паші )\nВсе на вищому рівні. Я ще точно не знаю, шо хочу, а Паша це все вже перетворив на готовий ескіз суто з моїх слів👌\n\nТак що за татуюваннями тільки до Паші","url":"https://maps.app.goo.gl/MKHEQEsigm8xwwtV6"},
{id:'daria',author:"Дар'я Черних",rating:5,originalLanguage:'uk',quote:'Зовсім нещодавно набивала одразу два тату в Павла ) все пройшло швидко і безболісно, дуже обережно робив майстер. А в мене одне тату було на руці (болюча зона).\n\nЯ дуже задоволена, заживає добре ) не можу налюбоватися ))))\n\nФото одразу після набивання☺️',url:'https://maps.app.goo.gl/tYrj1PABDP8kxuoc7'},
{id:'volodymyr',author:'Володимир',rating:5,originalLanguage:'uk',quote:'Зробив у Павла 3 тату + відновив стару.\nРоботою ДУЖЕ задоволений! Першій вже більше трьох років — виглядає як нова!)\nЗ новими ідеями йду одразу сюди!',url:'https://maps.app.goo.gl/poYHoHAVmTx25YJX9'},
{"id":"viktoriia-boiko","author":"Viktoriia Boiko","quote":"Робила майже всі тату у майстра Павла.\nДеяким тату вже 6 років, контури ідеальні!!!\n\nЯкість і швидкість просто на вищому рівні!!!","rating":5,"originalLanguage":"uk","url":"https://maps.app.goo.gl/iUZLvPL3n3oMRPRD6"},
{id:'sonic',author:'Sonic',rating:5,originalLanguage:'uk',quote:'Ходжу до Паші вже не перший рік, всі свої тату бʼю тут, це штук 5 точно! Майстер своє справи, приємні розмови! Супер клас топ! Буду ходити і ходити далі сюди! 🖤',url:'https://maps.app.goo.gl/vzfsLdnNCnxSLJBA9'},
{"id":"st-arosta","author":"St Arosta","quote":"Павло- майстер свого діла. Все пройшло класно, рекомендую!","rating":5,"originalLanguage":"uk","url":"https://maps.app.goo.gl/VULLQ1K1jTTc2A8E6"},
{id:'natali-latynska',author:'Natali Latynska',rating:5,originalLanguage:'en',quote:'The best of the best! )',url:'https://maps.app.goo.gl/s985Sji2EyNMrsA5A'},
{id:'victoria',author:'Виктория Давыденко',rating:5,originalLanguage:'uk',quote:'Паша, ти найкращий майстер тату евер\nЯкщо вам треба якісна тату, а ще допомога з ескізом — то вам точно сюди!',url:'https://maps.app.goo.gl/DXRPDrDJkPnhk5yf8'},
{id:'myla',author:'Мила Мережко',rating:5,originalLanguage:'uk',quote:'Не один «партачок» був виправлений Пашою, майстер своєї справи )\nНа фото крайнє тату яке перекривало невдалу роботу іншого майстра, і таких у мене кілька (помилки юності🫣) інші роботи самостійно сфотографувати не вдасться 🤣))\nДо нього консультувалася з іншими, мені говорили що це неможливо)\nДобре що є він і все неможливе стає реальним ))\nМрію в скорому часі потрапити до Павла знову, це вже залежність)\nІ ще плюс до професіональності що на вигляд такий брутальний дядько насправді такий милий і добрий )\nЩира рекомендація!!!',url:'https://maps.app.goo.gl/4hATgEy5YBUb9YzN7'},
];
export const studioDefaults={mapsUrl:'https://maps.app.goo.gl/Wh4vhs2vYa1cVsBw6',openingHours:'Щодня · 11:00–20:00',reviews:initialReviews};
export function isMapsUrl(value:string){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&((u.hostname==='maps.app.goo.gl'&&/^\/[A-Za-z0-9]+$/.test(u.pathname))||(['www.google.com','google.com'].includes(u.hostname)&&u.pathname.startsWith('/maps/')))}catch{return false}}
